### ISSUE TITLE
Multiple tag versions

### ISSUE THREAD

**Issue by guillaumebriday** [timbru31/docker-ruby-node#242]
Hey ! Thank you for these images.

I wonder if it's could be possible to automatically build images for every tags of the official ruby images ?

For exemple : 2.3.0-alpine with node inside

Because I work on multiple projects with different ruby version and I don't want to manually build image for each one.

Thank you in advance 👍

**Comment by timbru31** [comment]
Sure, I’ll add support for this

**Comment by timbru31** [comment]
Done with https://github.com/timbru31/docker-ruby-node/commit/0e88150629d00f921b0f4430d4b40ac5fb237f1a - let me know if you encounter any issues.
