### ISSUE TITLE
Adding ENV LANG C.UTF-8

### ISSUE THREAD

**Issue by sethiele** [timbru31/docker-ruby-node#342]
Hi,
is it possible to add `ENV LANG C.UTF-8` in the Docker files?

I have some issues without setting UTF-8 in the Docker file. For example: https://github.com/gjtorikian/html-proofer/issues/476

Thanks
Sebastian

**Comment by timbru31** [comment]
Hi Sebastian,

done!
New images should build now and be available in 30min-1hr.

**Comment by sethiele** [comment]
Awesome. Thanks!

**Comment by sethiele** [comment]
Hi @timbru31,
could you check the build process? There is no new build at https://hub.docker.com/r/timbru31/ruby-node 
Thanks

**Comment by timbru31** [comment]
Docker's build process is so unbelievable unreliable.
Images are built now. Have fun!
