### ISSUE TITLE
Ruby v2.6.x images are missing

### ISSUE THREAD

**Issue by pstaender** [timbru31/docker-ruby-node#477]
Hi! First, thank you for providing this handy docker images to all of us :)

I'm using ruby v2.6 but actually can't find any images for that version. Is this done on purpose or  just a mistake?

**Comment by timbru31** [comment]
Definitively a mistake! Unfortunately, dependabot (which automatically updates the images) recently messed up some tags. I'll take a look now.

**Comment by timbru31** [comment]
2.6 is back with the tags `2.6`, `2.6-slim`, and `2.6-alpine`. Thanks for letting me know.
