### ISSUE TITLE
2.7 only published arm64 and is missing 386 and amd64, thus breaking many of your downstream users

### ISSUE THREAD

**Issue by vorburger** [timbru31/docker-ruby-node#564]
Hello @timbru31 I wanted to let you know that we ran into https://github.com/openMF/community-app/issues/3323.

I suspsect that this may be because, as can be seen on https://hub.docker.com/r/timbru31/ruby-node/tags, you (or some infrastructure you use) has suddenly, about 6 hours ago from when I write this, published only a `linux/arm64` _OS/ARCH_ for tag 2.7, whereas for other versions, and up to very very recently, you've also published a `linux/amd64` (and `linux/386`) arch image variant.

**Comment by vorburger** [comment]
![timbru31](https://user-images.githubusercontent.com/298598/98040841-44165380-1e21-11eb-9e06-a7f4ed9ac7f1.png)

**Comment by timbru31** [comment]
This might be related to today's build failure, Docker's infra is sometimes a bit unreliable. I've restarted the pipeline.

**Comment by timbru31** [comment]
The mentioned tags are back, thanks for letting me know. I'll leave this issue open until I remove the fail-fast flag from the CI pipeline to ensure a failure does not cancel other builds.

**Comment by vorburger** [comment]
@timbru31 confirming it works again now.  -- FYI to anyone else running into the same problem and finding this issue in the future: You have to `docker rmi timbru31/ruby-node:2.7` to remove the "bad" _(ARM)_ image locally and cause it to re-fetch the "good" _(amd64)_.

Thank You very much for your quick reaction here.  You have unblocked the humanitarian open source project for financial inclusion! (https://github.com/openMF/community-app for https://www.fineract.dev)

**Comment by vorburger** [comment]
https://twitter.com/vorburger/status/1323739501152342024

**Comment by timbru31** [comment]
Glad this solved the issue - really appreciate your thanks and that my image is actually used for something useful :)

**Comment by timbru31** [comment]
Closing this issue, since I've set `fail-fast: false` which works as expected.
