### ISSUE TITLE
Upgrade to Node.js v14 LTS (Fermium)

### ISSUE THREAD

**Issue by timbru31** [timbru31/docker-ruby-node#567]
The next Node.js LTS release has been published. The Alpine builds are currently not available yet: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14046

**Comment by timbru31** [comment]
Technically speaking this would be a breaking change; Node.js upgrades are most of the time no problem though.
I'm now aware of at least one bigger project that uses these images, therefore pinging @vorburger - would an upgraded Node.js be a problem for openMF/community-app?

**Comment by bbaki** [comment]
Could we by change get this configurable? This change (upgrade to v14) actually broke our build and I believe there may be other people out there with a similar problem.
I'm looking for a ruby 2.7 node 12 image but I can't seem to find one :(

**Comment by timbru31** [comment]
Can you share any error message(s)?

**Comment by bbaki** [comment]
Ok, I've managed to circumnavigate the issue by just updating node-sass version. I thought it (node-sass version) was tight specifically to a specific node version (bad docs reading :p). However there might be more such issues and I still believe being able to do `ruby2.7node12` (i.e. have params) would be beneficial :)

**Comment by timbru31** [comment]
Yes, the big problem here is that at least for alpine the updates are spare (https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.12) at least for the non-edge branch.

**Comment by timbru31** [comment]
I've re-added Node.js 12 images. Example tags:
```
2.5-12 or 2.5-erbium
2.6-slim-12 or 2.6-slim-erbium
3.0-alpine-12 or 3.0-alpine-erbium

2.7 or 2.7-14 or 2.7-fermium
```
