### ISSUE TITLE
OEL Images??

### ISSUE THREAD

**Issue by poloka** [timbru31/docker-ruby-node#626]
@timbru31 what would you think about adding [oraclelinux](https://hub.docker.com/_/oraclelinux/tags) images for their supported platforms?
* [oraclelinux:8-slim](https://hub.docker.com/layers/library/oraclelinux/8-slim/images/sha256-6aca02f557113eacbc06a5ede0e71cab97f7feafb909b4b16be18970ace00b71?context=explore)
* [oraclelinux:9-slim](https://hub.docker.com/layers/library/oraclelinux/9-slim/images/sha256-8363ce227bea490538f3e1d64bc74f96f85b9266ec1adcbfab8478376964fa60?context=explore)

**Comment by timbru31** [comment]
Hi,

what are the benefits of this Linux distribution?

**Comment by timbru31** [comment]
Closing due to lack of feedback.  
If you are still requiring OEL images, please go ahead and explain your use case @poloka and I'm happy to re-open :)
