### ISSUE TITLE
Dockerhub description does not match github's

### ISSUE THREAD

**Issue by oubaydos** [timbru31/docker-ruby-node#634]
in github repository you have 'Ruby 3.0, 3.1 or 3.2 with Node.js 16 or 18 LTS Dockerfile' but in dockerhub you have 'Ruby 2.5, 2.6, 2.7 or 3.0 (RC) with Node.js 12 or 14 LTS Dockerfile' which confused me.
dockerhub repository need to be updated to include the newer versions.
Thanks

**Comment by timbru31** [comment]
Thanks for the hint, README updated.
